# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d2158f8dca70e053a52c817b6eeb367414bd91e46410bdad36ea1f882cc838a4e338697e2dd4f140d8af177ce70ff1d976b7874671de3a56eed149d2c8f70dbd

test:
  secret_key_base: 96b0ee26e702af97bace9507d776c08d5b4029355aabe6699995f77e57d098e7f965435377c8c0324ee116fa4391b14d078c7b7ea8c7b741812908101edfc61a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
